### PR TITLE
Aligning to central

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by grgrzybek** [comment]
Wow - thanks for bringing it into oss.sonatype!

**Comment by grgrzybek** [comment]
Maybe we should change `<groupId>com.github.grgrzybek</groupId>` into something less personal? ;) Did you setup oss.sonatype.org groupId already? (I don't know precisely how it is done)

**Comment by hazendaz** [comment]
I got it setup already but that doesn't mean this project has to use it.  I'm not sure we are really allowed to use something less personal due to the hosting location or through purchase of a domain.  I've seen a number of projects this way.  Others took their personal location and changed it on github to be project specific.  Same could be done here.  I believe it is still free...

--- Original Message ---

**Comment by grgrzybek** [comment]
ah ok :) let's leave it like this.

best regards and thanks for help!
Grzegorz

2015-05-07 13:36 GMT+02:00 Jeremy Landis <notifications@github.com>:

**Pull request merged**
